### ISSUE TITLE
Problem with the method "propagate" in "MessagePassing" class

### ISSUE THREAD

**Issue by aliloloee** [ZeqingJin/MeshPhysicsGNN-NeuralOps#1]
Executing the blocks of codes according to the file _main.ipynb_ in _main_ folder on my colab, I run into a problem while executing this line of code :
`test_losses, losses, velo_val_losses, best_model, best_test_loss, test_loader = train(dataset, device, stats_list, args)`

This line of code then goes back to the _forward_ method of the class _ProcessorLayer(MessagePassing)_ . The problem occurs when reaching this line `out, updated_edges = self.propagate(edge_index, x = x, edge_attr = edge_attr, size = size)`. 

This is the error : `TypeError: propagate() got an unexpected keyword argument 'x'`

Any idea how to overcome this ?

**Comment by MohsenZahedi** [comment]
I receive the same error when I run  that block of the code. Here is the snapshot of my colab . 


![1](https://github.com/ZeqingJin/MeshPhysicsGNN-NeuralOps/assets/105466476/a91ce74d-16e2-4360-9053-5644892ea3af)

**Comment by ZeqingJin** [comment]
The updated code:

out, updated_edges = self.aggregate( edge_attr, edge_index, size ) # out has the shape of [node_num, out_channels]
